 name: screen_off_app
 description: "A new Flutter project."
 publish_to: 'none'
 version: 1.0.0+1

 environment:
   sdk: ^3.8.1

 dependencies:
   flutter:
     sdk: flutter
   cupertino_icons: ^1.0.8
   google_fonts: ^6.2.1
   flutter_launcher_icons: ^0.14.4

 dev_dependencies:
   flutter_test:
     sdk: flutter
   

 flutter_native_splash:
   color: "#000000"
   image: assets/splash/logo.png
   android: true

 flutter_icons:
   android: true
   ios: false
   image_path: assets/icon/logo.png

 flutter:
   uses-material-design: true
   assets:
     - assets/splash/logo.png
