name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v4

      # 2. Install Flutter SDK (stable channel)
      - name: Install Flutter SDK
        run: |
          git clone --depth=1 https://github.com/flutter/flutter.git -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      # 3. Get Flutter dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 4. Build a release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 5. Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
