name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v4

      # 2. Set up Flutter SDK (stable channel)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 3. Install your Dart/Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. (Optional) Verify formatting
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      # 5. Static analysis
      - name: Analyze project
        run: flutter analyze

      # 6. Run your tests
      - name: Run tests
        run: flutter test

      # 7. (Optional) Build a release APK for Android
      - name: Build Android APK
        run: flutter build apk --release
