name: Flutter Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Install Flutter SDK
      - name: Install Flutter
        run: |
          git clone --depth=1 https://github.com/flutter/flutter.git -b stable
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      # 3. Get dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 4. Build release APK
      - name: Build APK
        run: flutter build apk --release
