name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository (persist-credentials is true by default)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Flutter SDK (stable channel)
      - name: Install Flutter SDK
        run: |
          git clone --depth=1 https://github.com/flutter/flutter.git -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      # 3. Fetch dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 4. Build a release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 5. Upload the APK as an artifact (uses v4 to avoid deprecation)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 6. Commit the APK back to the repo (optional, will bloat your history)
      # - name: Add APK to repo
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     cp build/app/outputs/flutter-apk/app-release.apk .
      #     git add app-release.apk
      #     git commit -m "Add latest release APK" || echo "No changes to commit"
      #     git push
