name: Flutter Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Install Flutter by cloning the stable channel
      - name: Install Flutter SDK
        run: |
          git clone --depth=1 https://github.com/flutter/flutter.git -b stable
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      # 3. (Optional) Verify the Flutter install
      - name: Flutter doctor
        run: flutter doctor

      # 4. Install project dependencies
      - name: Pub get
        run: flutter pub get

      # 5. Run any tests you have
      - name: Run tests
        run: flutter test

      # 6. Build a release APK for Android
      - name: Build Release APK
        run: flutter build apk --release
